config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  
  resources :tasks do
    put :complete, on:  :member
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
    PRIORITIES = [
        ['Later', 1],
        ['Next', 2],
        ['Now', 3]
    ]

    def complete!
        self.completed = true
        save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where(completed: false).order('priority DESC')
    @completed_tasks = Task.where(completed: true).order('updated_at')
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new task_params

    @task.save

    redirect_to tasks_path

  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    @task = Task.find params[:id]

    @task.update_attributes task_params # обновляем 

    redirect_to tasks_path  # редирект на список задач
  end

  def complete
    @task = Task.find params[:id]

    @task.complete!

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find params[:id]

    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit([
      :title, :priority, :completed
    ])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "container"><div class = "row"><%= yield %></div></div>

</body>
</html>

app/views/tasks/_form.html.erb
<div class = "col-md-6">
<%= simple_form_for @task do |f| %>
    <p><%= f.input :title %></p>
    <p><%= f.select :priority, Task::PRIORITIES %></p>
    <p><%= f.input :completed %></p>
    <p><%= f.button :submit %></p>
<% end %>

app/views/tasks/_task.html.erb
<div class = "task priority_<%= task.priority %> completed_<%= task.completed %>">
    <p><span class = "title"><%= task.title %></span>
    <%= link_to content_tag('span', '', class: 'fa fa-pencil'), edit_task_path(task), class: 'action' %>
    <%= link_to content_tag('span', '', class: 'fa fa-trash'), task, method: :delete, class: 'action' %>
    <%= link_to content_tag('span', '', class: 'fa fa-check-square-o'), complete_task_path(task), data: {metod: :put}, class: 'done action'%>

app/views/tasks/complete.html.erb
<h1>Tasks#complete</h1>
<p>Find me in app/views/tasks/complete.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class = "col-md-12">
    <h1>Edit Task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class = "buffer-top">
    <%= link_to 'New task', new_task_path(), class: 'btn btn-primary' %>
</div>
<div class = "buffer-top">
    <% @tasks.each do |task| %>
        <%= render partial: 'task', object: task %>
    <% end %>

    <hr />

    <% @completed_tasks.each do |task| %>
        <%= render partial: 'task', object: task %>
    <% end %>
</div>
</div>

app/views/tasks/new.html.erb
<div class = "col-md-12">
    <h1>New Task</h1>
</div>

<%= render 'form' %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>